services:
  haproxy:
    build:
      context: .
      args:
        - HAPROXY_TAG=${HAPROXY_TAG:-3.2.4}
    container_name: haproxy-rpc-proxy
    restart: unless-stopped
    environment:
      # Comma-separated list of upstreams (host:port)
      - RPC_HTTP_UPSTREAMS=${RPC_HTTP_UPSTREAMS:-chi1.cracknode.com:8899}
      - RPC_GRPC_UPSTREAMS=${RPC_GRPC_UPSTREAMS:-chi1.cracknode.com:10000}
      - LISTEN_HTTP_PORT=${LISTEN_HTTP_PORT:-8899}
      - LISTEN_GRPC_PORT=${LISTEN_GRPC_PORT:-10000}
      - LISTEN_HTTP_TLS_ENABLE=${LISTEN_HTTP_TLS_ENABLE:-false}
      - LISTEN_HTTP_TLS_PORT=${LISTEN_HTTP_TLS_PORT:-8443}
      - LISTEN_GRPC_TLS_ENABLE=${LISTEN_GRPC_TLS_ENABLE:-false}
      - LISTEN_GRPC_TLS_PORT=${LISTEN_GRPC_TLS_PORT:-10001}
      - STATS_PORT=${STATS_PORT:-8404}
      - STATS_USER=${STATS_USER:-admin}
      - STATS_PASS=${STATS_PASS:-admin}
      - HEALTH_RISE=${HEALTH_RISE:-2}
      - HEALTH_FALL=${HEALTH_FALL:-3}
      - ADMIN_SOCKET_TCP=${ADMIN_SOCKET_TCP:-true}
      - ADMIN_SOCKET_PORT=${ADMIN_SOCKET_PORT:-9999}
      - MAXCONN=${MAXCONN:-30000}
      - ULIMIT_N=${ULIMIT_N:-65000}
      - TLS_CERT_FILE=${TLS_CERT_FILE:-/etc/haproxy/certs/server.pem}
      - TLS_CLIENT_CA_FILE=${TLS_CLIENT_CA_FILE:-}
      - TLS_CLIENT_VERIFY=${TLS_CLIENT_VERIFY:-none}
      - TLS_MIN_VER=${TLS_MIN_VER:-TLSv1.2}
      - RPC_HTTP_UPSTREAMS_TLS=${RPC_HTTP_UPSTREAMS_TLS:-false}
      - RPC_HTTP_UPSTREAMS_VERIFY=${RPC_HTTP_UPSTREAMS_VERIFY:-none}
      - RPC_GRPC_UPSTREAMS_TLS=${RPC_GRPC_UPSTREAMS_TLS:-false}
      - RPC_GRPC_UPSTREAMS_VERIFY=${RPC_GRPC_UPSTREAMS_VERIFY:-none}
      - RPC_HTTP_BALANCE=${RPC_HTTP_BALANCE:-roundrobin}
      - RPC_GRPC_BALANCE=${RPC_GRPC_BALANCE:-roundrobin}
      - RPC_HTTP_ENABLE_HTTP_MODE=${RPC_HTTP_ENABLE_HTTP_MODE:-false}
      - RPC_HTTP_HEALTH_HTTP=${RPC_HTTP_HEALTH_HTTP:-false}
      - RPC_HTTP_HEALTH_HOST=${RPC_HTTP_HEALTH_HOST:-localhost}
    ports:
      - "${LISTEN_HTTP_PORT:-8899}:${LISTEN_HTTP_PORT:-8899}"
      - "${LISTEN_GRPC_PORT:-10000}:${LISTEN_GRPC_PORT:-10000}"
      - "${LISTEN_HTTP_TLS_PORT:-8443}:${LISTEN_HTTP_TLS_PORT:-8443}"
      - "${LISTEN_GRPC_TLS_PORT:-10001}:${LISTEN_GRPC_TLS_PORT:-10001}"
      - "${STATS_PORT:-8404}:${STATS_PORT:-8404}"
      - "${ADMIN_SOCKET_PORT:-9999}:${ADMIN_SOCKET_PORT:-9999}"
    volumes:
      - ./certs:/etc/haproxy/certs:ro
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test: ["CMD-SHELL", "haproxy -c -f /usr/local/etc/haproxy/haproxy.cfg || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

